### Importación de datos

In [76]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [77]:
tienda2.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175

In [78]:
tienda3.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Secadora de ropa,Electrodomésticos,1285100.0,66600.0,17/12/2021,Camila Rivera,Santa Marta,4,Tarjeta de crédito,4,11.24079,-74.19904
1,Mesa de noche,Muebles,290100.0,13600.0,10/02/2021,Maria Alfonso,Cali,3,Tarjeta de crédito,1,3.43722,-76.52250
2,Guitarra acústica,Instrumentos musicales,303500.0,17400.0,22/01/2023,Lucas Olivera,Bogotá,5,Tarjeta de crédito,3,4.60971,-74.08175
3,Balón de voleibol,Deportes y diversión,58800.0,3300.0,22/03/2022,Pedro Gomez,Barranquilla,4,Tarjeta de crédito,6,10.96854,-74.78132
4,Armario,Muebles,521100.0,25900.0,12/01/2022,Blanca Ramirez,Bogotá,1,Tarjeta de crédito,1,4.60971,-74.08175

In [79]:
tienda4.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Lavavajillas,Electrodomésticos,1084800.0,56000.0,11/11/2022,Rafael Acosta,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175
1,Cama box,Muebles,473800.0,25400.0,03/01/2020,Izabela de León,Cúcuta,5,Tarjeta de crédito,2,7.89391,-72.50782
2,Balón de baloncesto,Deportes y diversión,23700.0,0.0,25/12/2022,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359
3,Modelado predictivo,Libros,57700.0,1300.0,23/11/2021,Lucas Olivera,Medellín,3,Nequi,1,6.25184,-75.56359
4,Auriculares,Electrónicos,138900.0,5600.0,25/04/2022,Blanca Ramirez,Bogotá,4,Tarjeta de crédito,7,4.60971,-74.08175

# 1. Análisis de facturación

In [80]:
# calcular el ingreso total de cada tienda. 
# Sumando los valores de la columna Precio de cada conjunto de datos de la tienda para estimar los ingresos.

In [81]:
suma_tienda = tienda['Precio'].sum()
suma_tienda2 = tienda2['Precio'].sum()
suma_tienda3 = tienda3['Precio'].sum()
suma_tienda4 = tienda4['Precio'].sum()
print(f"Suma de los precios de tienda: {suma_tienda}")
print(f"Suma de los precios de tienda2: {suma_tienda2}")
print(f"Suma de los precios de tienda3: {suma_tienda3}")
print(f"Suma de los precios de tienda4: {suma_tienda4}")

Suma de los precios de tienda: 1150880400.0
Suma de los precios de tienda2: 1116343500.0
Suma de los precios de tienda3: 1098019600.0
Suma de los precios de tienda4: 1038375700.0

# 2. Ventas por categoría

In [82]:
url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"
# calcular la cantidad de productos vendidos por categoría en cada tienda. La idea es agrupar los datos por categoría
#  y contar el número de ventas de cada tipo, mostrando las categorías más populares de cada tienda.

########################## conteo tienda 1 #####################################

# ejemplo en el archivo  "tienda.csv" hay la columna: Producto, categoria_producto 
tienda = pd.read_csv(url, usecols=['Producto', 'Categoría del Producto'])
# Contar cuántos productos se vendieron por categoría
conteo_tienda_1 = tienda.groupby('Categoría del Producto').count().reset_index()
# Renombrar la columna para que sea más clara
conteo_tienda_1 = conteo_tienda_1.rename(columns={'Producto': 'cantidad_vendida'})

########################## conteo tienda 2 #####################################

# ejemplo en el archivo  "tienda.csv" hay la columna: Producto, categoria_producto 
tienda_2 = pd.read_csv(url2, usecols=['Producto', 'Categoría del Producto'])
# Contar cuántos productos se vendieron por categoría
conteo_tienda_2 = tienda_2.groupby('Categoría del Producto').count().reset_index()
# Renombrar la columna para que sea más clara
conteo_tienda_2 = conteo_tienda_2.rename(columns={'Producto': 'cantidad_vendida'})

########################## conteo tienda 3 #####################################

# ejemplo en el archivo  "tienda.csv" hay la columna: Producto, categoria_producto 
tienda_3 = pd.read_csv(url3, usecols=['Producto', 'Categoría del Producto'])
# Contar cuántos productos se vendieron por categoría
conteo_tienda_3 = tienda_3.groupby('Categoría del Producto').count().reset_index()
# Renombrar la columna para que sea más clara
conteo_tienda_3 = conteo_tienda_3.rename(columns={'Producto': 'cantidad_vendida'})

########################## conteo tienda 4 #####################################

# ejemplo en el archivo  "tienda.csv" hay la columna: Producto, categoria_producto 
tienda_4 = pd.read_csv(url4, usecols=['Producto', 'Categoría del Producto'])
# Contar cuántos productos se vendieron por categoría
conteo_tienda_4 = tienda_4.groupby('Categoría del Producto').count().reset_index()
# Renombrar la columna para que sea más clara
conteo_tienda_4 = conteo_tienda_4.rename(columns={'Producto': 'cantidad_vendida'})

print("*********** Ventas por categoria de la tienda 1 ************")
print(conteo_tienda_1)
print("*********** Ventas por categoria de la tienda 2 ************")
print(conteo_tienda_2)
print("*********** Ventas por categoria de la tienda 3 ************")
print(conteo_tienda_3)
print("*********** Ventas por categoria de la tienda 4 ************")
print(conteo_tienda_4)

*********** Ventas por categoria de la tienda 1 ************
    Categoría del Producto  cantidad_vendida
0  Artículos para el hogar               171
1     Deportes y diversión               284
2        Electrodomésticos               312
3             Electrónicos               448
4   Instrumentos musicales               182
5                 Juguetes               324
6                   Libros               173
7                  Muebles               465
*********** Ventas por categoria de la tienda 2 ************
    Categoría del Producto  cantidad_vendida
0  Artículos para el hogar               181
1     Deportes y diversión               275
2        Electrodomésticos               305
3             Electrónicos               422
4   Instrumentos musicales               224
5                 Juguetes               313
6                   Libros               197
7                  Muebles               442
*********** Ventas por categoria de la tienda 3 ************
    Categoría del Producto  cantidad_vendida
0  Artículos para el hogar               177
1     Deportes y diversión               277
2        Electrodomésticos               278
3             Electrónicos               451
4   Instrumentos musicales               177
5                 Juguetes               315
6                   Libros               185
7                  Muebles               499
*********** Ventas por categoria de la tienda 4 ************
    Categoría del Producto  cantidad_vendida
0  Artículos para el hogar               201
1     Deportes y diversión               277
2        Electrodomésticos               254
3             Electrónicos               451
4   Instrumentos musicales               170
5                 Juguetes               338
6                   Libros               187
7                  Muebles               480

# 3. Calificación promedio de la tienda

In [83]:
# Debes calcular las calificaciones promedio de los clientes para cada tienda. 
# El objetivo es conocer la satisfacción del cliente con los productos vendidos.

tienda = pd.read_csv(url, usecols=['Calificación'])
tienda_2 = pd.read_csv(url2, usecols=['Calificación'])
tienda_3 = pd.read_csv(url3, usecols=['Calificación'])
tienda_4 = pd.read_csv(url4, usecols=['Calificación'])
# Calcular el promedio de la columna 'calificacion'
promedio = tienda['Calificación'].mean()
promedio_2 = tienda_2['Calificación'].mean()
promedio_3 = tienda_3['Calificación'].mean()
promedio_4 = tienda_4['Calificación'].mean()

print(f"Promedio de calificaciones de los clientes para la tienda 1: {promedio}")
print(f"Promedio de calificaciones de los clientes para la tienda 2: {promedio_2}")
print(f"Promedio de calificaciones de los clientes para la tienda 3: {promedio_3}")
print(f"Promedio de calificaciones de los clientes para la tienda 4: {promedio_4}")

Promedio de calificaciones de los clientes para la tienda 1: 3.976685036032217
Promedio de calificaciones de los clientes para la tienda 2: 4.037303942348453
Promedio de calificaciones de los clientes para la tienda 3: 4.048325561678677
Promedio de calificaciones de los clientes para la tienda 4: 3.9957591178965224

# 4. Productos más y menos vendidos

In [84]:
# debes identificar qué productos fueron los más vendidos y los menos vendidos en cada tienda. 
# Visualiza los resultados para que quede claro qué productos destacaron en ventas en cada tienda
# ejemplo en el archivo  "tienda.csv" hay la columna: Producto 

print("*********** Producto mas y menos vendido de la tienda 1 ************")
tienda = pd.read_csv(url, usecols=['Producto'])
# Contar cuántas veces se vendió cada producto
conteo = tienda['Producto'].value_counts()
print(conteo)
# Obtener el producto más vendido
mas_vendido = conteo.idxmax()
cant_mas_vendido = conteo.max()

# Obtener el producto menos vendido
menos_vendido = conteo.idxmin()
cant_menos_vendido = conteo.min()

print(f"🥇 Producto más vendido: {mas_vendido} ({cant_mas_vendido} ventas)")
print(f"🔻 Producto menos vendido: {menos_vendido} ({cant_menos_vendido} venta/s)")

*********** Producto mas y menos vendido de la tienda 1 ************
Producto
Microondas                     60
TV LED UHD 4K                  60
Armario                        60
Secadora de ropa               58
Mesa de noche                  56
Bloques de construcción        56
Balón de baloncesto            55
Bicicleta                      54
Vaso térmico                   54
Refrigerador                   54
Impresora                      54
Batería                        53
Cubertería                     52
Carrito de control remoto      52
Modelado predictivo            51
Auriculares                    50
Ajedrez de madera              49
Iphone 15                      49
Lavavajillas                   48
Lavadora de ropa               47
Guitarra eléctrica             47
Guitarra acústica              46
Sofá reclinable                46
Silla de oficina               46
Estufa                         45
Cama box                       44
Kit de bancas                  44
Smart TV                       44
Cama king                      44
Cubo mágico 8x8                44
Mesa de centro                 44
Set de ollas                   43
Smartwatch                     43
Juego de mesa                  43
Balón de voleibol              42
Dashboards con Power BI        42
Tablet ABXY                    42
Sillón                         41
Iniciando en programación      41
Set de vasos                   41
Asistente virtual              40
Muñeca bebé                    40
Mesa de comedor                40
Dinosaurio Rex                 40
Cuerda para saltar             40
Mochila                        39
Ciencia de datos con Python    39
Pandereta                      36
Olla de presión                35
Auriculares con micrófono      33
Celular ABXY                   33
Name: count, dtype: int64
🥇 Producto más vendido: Microondas (60 ventas)
🔻 Producto menos vendido: Auriculares con micrófono (33 venta/s)

In [85]:
print("*********** Producto mas y menos vendido de la tienda 2 ************")
tienda_2 = pd.read_csv(url2, usecols=['Producto'])
# Contar cuántas veces se vendió cada producto
conteo = tienda_2['Producto'].value_counts()
print(conteo)
# Obtener el producto más vendido
mas_vendido = conteo.idxmax()
cant_mas_vendido = conteo.max()

# Obtener el producto menos vendido
menos_vendido = conteo.idxmin()
cant_menos_vendido = conteo.min()

print(f"🥇 Producto más vendido: {mas_vendido} ({cant_mas_vendido} ventas)")
print(f"🔻 Producto menos vendido: {menos_vendido} ({cant_menos_vendido} venta/s)")

*********** Producto mas y menos vendido de la tienda 2 ************
Producto
Iniciando en programación      65
Microondas                     62
Batería                        61
Guitarra acústica              58
Pandereta                      58
Secadora de ropa               57
Iphone 15                      55
Bloques de construcción        54
Armario                        54
Set de ollas                   52
Cuerda para saltar             50
Lavadora de ropa               49
Silla de oficina               49
Refrigerador                   49
Muñeca bebé                    48
Carrito de control remoto      47
Guitarra eléctrica             47
Cama box                       47
Vaso térmico                   47
Modelado predictivo            46
Balón de voleibol              46
Set de vasos                   46
Lavavajillas                   46
Kit de bancas                  45
Cama king                      45
Bicicleta                      45
Mochila                        45
Cubo mágico 8x8                45
Ajedrez de madera              45
Mesa de centro                 45
TV LED UHD 4K                  45
Tablet ABXY                    44
Smartwatch                     44
Mesa de noche                  44
Olla de presión                44
Auriculares con micrófono      44
Sofá reclinable                44
Dashboards con Power BI        43
Ciencia de datos con Python    43
Balón de baloncesto            42
Estufa                         42
Dinosaurio Rex                 42
Celular ABXY                   41
Smart TV                       40
Cubertería                     39
Asistente virtual              38
Auriculares                    37
Sillón                         35
Mesa de comedor                34
Impresora                      34
Juego de mesa                  32
Name: count, dtype: int64
🥇 Producto más vendido: Iniciando en programación (65 ventas)
🔻 Producto menos vendido: Juego de mesa (32 venta/s)

In [86]:
print("*********** Producto mas y menos vendido de la tienda 3 ************")
tienda_3 = pd.read_csv(url3, usecols=['Producto'])
# Contar cuántas veces se vendió cada producto
conteo = tienda_3['Producto'].value_counts()
print(conteo)
# Obtener el producto más vendido
mas_vendido = conteo.idxmax()
cant_mas_vendido = conteo.max()

# Obtener el producto menos vendido
menos_vendido = conteo.idxmin()
cant_menos_vendido = conteo.min()

print(f"🥇 Producto más vendido: {mas_vendido} ({cant_mas_vendido} ventas)")
print(f"🔻 Producto menos vendido: {menos_vendido} ({cant_menos_vendido} venta/s)")

*********** Producto mas y menos vendido de la tienda 3 ************
Producto
Kit de bancas                  57
Mesa de comedor                56
Cama king                      56
Set de ollas                   55
Mesa de noche                  55
Smart TV                       54
Estufa                         53
Cuerda para saltar             53
Modelado predictivo            53
Carrito de control remoto      52
Lavavajillas                   52
Bicicleta                      52
Juego de mesa                  52
Pandereta                      51
Impresora                      50
Refrigerador                   50
Balón de baloncesto            50
Armario                        49
Balón de voleibol              48
Tablet ABXY                    48
Sillón                         47
Guitarra acústica              47
Olla de presión                47
Ajedrez de madera              47
Ciencia de datos con Python    46
Iphone 15                      46
Dinosaurio Rex                 46
Silla de oficina               46
Smartwatch                     46
Cama box                       46
Iniciando en programación      46
Secadora de ropa               45
Sofá reclinable                45
Celular ABXY                   44
Cubo mágico 8x8                44
Auriculares                    43
TV LED UHD 4K                  42
Mesa de centro                 42
Lavadora de ropa               42
Batería                        41
Dashboards con Power BI        40
Cubertería                     39
Muñeca bebé                    39
Auriculares con micrófono      39
Asistente virtual              39
Vaso térmico                   38
Guitarra eléctrica             38
Set de vasos                   36
Mochila                        36
Microondas                     36
Bloques de construcción        35
Name: count, dtype: int64
🥇 Producto más vendido: Kit de bancas (57 ventas)
🔻 Producto menos vendido: Bloques de construcción (35 venta/s)

In [87]:
print("*********** Producto mas y menos vendido de la tienda 2 ************")
tienda_4 = pd.read_csv(url4, usecols=['Producto'])
# Contar cuántas veces se vendió cada producto
conteo = tienda_4['Producto'].value_counts()
print(conteo)
# Obtener el producto más vendido
mas_vendido = conteo.idxmax()
cant_mas_vendido = conteo.max()

# Obtener el producto menos vendido
menos_vendido = conteo.idxmin()
cant_menos_vendido = conteo.min()

print(f"🥇 Producto más vendido: {mas_vendido} ({cant_mas_vendido} ventas)")
print(f"🔻 Producto menos vendido: {menos_vendido} ({cant_menos_vendido} venta/s)")

*********** Producto mas y menos vendido de la tienda 2 ************
Producto
Cama box                       62
Cubertería                     59
Dashboards con Power BI        56
Cama king                      56
Carrito de control remoto      55
Mesa de comedor                55
Mesa de noche                  55
Smart TV                       54
Bloques de construcción        54
Pandereta                      52
Impresora                      50
Modelado predictivo            50
Asistente virtual              50
Set de ollas                   50
Balón de baloncesto            50
Vaso térmico                   48
Iphone 15                      48
Muñeca bebé                    48
Batería                        48
Balón de voleibol              48
Juego de mesa                  48
Microondas                     48
Estufa                         47
Cubo mágico 8x8                47
Sofá reclinable                47
Dinosaurio Rex                 47
Olla de presión                46
Set de vasos                   46
Tablet ABXY                    45
Sillón                         45
Bicicleta                      45
Mesa de centro                 44
Auriculares                    44
Lavavajillas                   43
Cuerda para saltar             43
Iniciando en programación      43
Mochila                        43
Auriculares con micrófono      42
Kit de bancas                  42
TV LED UHD 4K                  40
Secadora de ropa               40
Silla de oficina               40
Celular ABXY                   39
Ajedrez de madera              39
Smartwatch                     39
Lavadora de ropa               38
Refrigerador                   38
Ciencia de datos con Python    38
Guitarra acústica              37
Armario                        34
Guitarra eléctrica             33
Name: count, dtype: int64
🥇 Producto más vendido: Cama box (62 ventas)
🔻 Producto menos vendido: Guitarra eléctrica (33 venta/s)

# 5. Envío promedio por tienda